### ISSUE TITLE
README link is to wrong webpage

### ISSUE THREAD

**Issue by wholden** [pololu/pololu-tic-software#1]
In the README, it says:

Installers for this software are available for download from the <link>Tic Stepper Motor Controller User's Guide.</link>

The webpage links to the user guide for Pololu USB AVR Programmer v2 User’s Guide. (https://www.pololu.com/docs/0J67)  

I guess it should link here instead: https://www.pololu.com/docs/0J71

**Comment by DavidEGrayson** [comment]
Thanks for letting us know.  It is fixed now.
