### ISSUE TITLE
API documentation 

### ISSUE THREAD

**Issue by stephanschulz** [pololu/pololu-tic-software#10]
Hello. 

Sorry for posting so many issues but i am very excited about your tic controllers and hope to make them my new goto stepper driver. 
Do you have a list of all available commands i can set via my custom c++ app?
I am able to include the code of [this example](https://www.pololu.com/docs/0J71/12.11) in to my c++ code but am not sure what commands would set acceleration, de-energize, resume, max speed, etc (all the controls i see in the gui app)

thanks a bunch.

**Comment by DavidEGrayson** [comment]
The comments in tic.hpp and tic.h serve as documentation.  You can also install Doxygen and run `doxygen` at the top level to generate documentation in HTML form from those comments.
