### ISSUE TITLE
Simple circuit for bidirectional level shifting 5V to 3.3V for I2C

### ISSUE THREAD

**Issue by mjmeans** [pololu/pololu-tic-software#3]
Simple and useful to connect Tic to Raspberry Pi 3 I2C. Give it a try.
http://www.hobbytronics.co.uk/mosfet-voltage-level-converter

Maybe include this circuit in the manual.

**Comment by DavidEGrayson** [comment]
We only use GitHub issues to discuss bugs and features requests for the software.  For general discussion about the Tic, please post to our forum:

https://forum.pololu.com/

(Also, you shouldn't need a level converter in that setup because the Tic's I²C pins will recognize 3.3 V as high.)

**Comment by mjmeans** [comment]
I'm signed up too many forums as it is. All the passwords are tedious, and all the spam and other notifications generated from the various forums is annoying and a waste of my time. The signal to noise ratio is just too horrible. And I don't use facebook and other social sites either; and I don't use SSO services for the same reasons. As for the offered circuit, you can take it or leave it. I thought the information would be useful, so I posted it here. Do what you want with it. But I see no reason to join your forums to post a single thread.
