### ISSUE TITLE
current position resets to 0

### ISSUE THREAD

**Issue by tkottary** [pololu/pololu-tic-software#5]
How do I resume the tic at the last position after the tic was powered off? I am using tic to drive a stepper motor which does not work if the position is negative. Given that tic reset to 0, I don't have any workaround to this.

**Comment by DavidEGrayson** [comment]
If you know what position your Tic was in when you powered it off, you can use the `--halt-and-set-position` option of `ticcmd` to set its current position.  if that does not answer your question, please post on our [forum](https://forum.pololu.com/).  GitHub issues are used to keep track of specific bugs and feature requests for the Tic software.
